# Generated by Django 4.2.20 on 2025-04-29 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books_movies_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isMovie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='isBook',
        ),
        migrations.AddField(
            model_name='book',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books_movies_api.movie'),
        ),
    ]
