# Generated by Django 5.2 on 2025-05-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_movies_api', '0002_remove_book_ismovie_remove_movie_isbook_book_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.IntegerField(),
        ),
    ]
