# Generated by Django 5.2 on 2025-05-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_movies_api', '0003_alter_book_date_alter_movie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='remote_url',
            field=models.URLField(blank=True, help_text='Internal: direct URL of the book cover image'),
        ),
    ]
